In [1]:
import pandas as pd
import numpy as np

load dataframe

In [28]:
train = pd.read_csv('all_data_with_sentiment_FINAL.csv')

In [29]:
train = train.sort_values(['date', 'tic'],
              ascending = [True, True])

add random Variable

In [30]:
# Add a new column 'random' with random values between 0 and 1
train['random'] = np.random.rand(len(train))

save dataframe

In [31]:
int(.8 *len(train))

74472

In [32]:
len(train["tic"].unique())

30

In [33]:
#function to find the number closest from https://www.geeksforgeeks.org/find-number-closest-n-divisible-m/
# to n and divisible by m
def closestNumber(n, m) :
    # Find the quotient
    q = int(n / m)
     
    # 1st possible closest number
    n1 = m * q
     
    # 2nd possible closest number
    if((n * m) > 0) :
        n2 = (m * (q + 1))
    else :
        n2 = (m * (q - 1))
     
    # if true, then n1 is the required closest number
    if (abs(n - n1) < abs(n - n2)) :
        return n1
     
    # else n2 is the required closest number
    return n2

In [34]:
closestNumber(int(.8 *len(train)), len(train["tic"].unique()))

74460

In [35]:
train_set, test_set= np.split(train, [closestNumber(int(.8 *len(train)), len(train["tic"].unique()))])

In [36]:
train_set

,date,tic,open,high,low,close,volume,day,macd,boll_ub,...,dx_30,close_30_sma,close_60_sma,vix,change,stocktwitsPosts,stocktwitsLikes,stocktwitsImpressions,stocktwitsSentiment,random
0,2021-11-24 14:00:00,AAPL,159.380,159.703,158.862,159.085,3513469.0,5.0,0.000000,160.308182,...,100.000000,159.085000,159.085000,85.622,-0.591471,102.0,132.0,361612.0,0.532856,0.086380
25,2021-11-24 14:00:00,ABBV,110.972,111.131,110.731,110.946,252882.0,5.0,0.000000,111.317357,...,100.000000,110.946000,110.946000,85.622,-0.415652,2.0,0.0,8971.0,0.361184,0.314486
22,2021-11-24 14:00:00,ABT,121.060,121.158,120.628,120.826,114943.0,5.0,0.000000,121.576372,...,100.000000,120.826000,120.826000,85.622,-0.504206,0.0,0.0,0.0,0.276325,0.194959
20,2021-11-24 14:00:00,AMD,155.630,156.000,154.440,155.055,2967827.0,5.0,0.000000,158.835572,...,100.000000,155.055000,155.055000,85.622,-0.025659,93.0,185.0,229760.0,0.526198,0.827423
19,2021-11-24 14:00:00,AMZN,178.733,179.239,178.000,178.330,1212440.0,5.0,0.000000,160.308182,...,100.000000,178.330000,178.330000,85.622,0.277621,42.0,49.0,32586.0,0.537884,0.600565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74440,2023-04-26 10:00:00,PM,97.618,97.670,97.226,97.457,110610.0,1.0,0.161388,98.562607,...,0.846250,96.521633,97.742217,42.076,-0.320672,3.0,0.0,40389.0,0.490000,0.611980
74432,2023-04-26 10:00:00,T,17.247,17.291,17.144,17.160,2851143.0,1.0,-0.279006,18.003779,...,47.806766,17.503700,18.472467,42.076,-0.784263,2.0,0.0,11114.0,0.625000,0.863384
74430,2023-04-26 10:00:00,TSLA,156.230,156.380,153.210,154.371,20803762.0,1.0,-3.227609,167.359940,...,56.610681,162.472767,173.321533,42.076,0.000421,25.0,56.0,19134.0,0.482500,0.339601
74445,2023-04-26 10:00:00,TSM,81.238,81.244,80.866,81.065,880630.0,1.0,-1.360288,86.270911,...,52.078250,85.084433,86.054167,42.076,-0.958122,1.0,0.0,8899.0,0.633300,0.992581
74453,2023-04-26 10:00:00,V,231.465,231.482,227.783,227.878,386850.0,1.0,-0.656645,234.512697,...,26.038398,232.067100,231.977533,42.076,1.284074,4.0,0.0,225683.5,0.665750,0.929223

In [37]:
test_set

,date,tic,open,high,low,close,volume,day,macd,boll_ub,...,dx_30,close_30_sma,close_60_sma,vix,change,stocktwitsPosts,stocktwitsLikes,stocktwitsImpressions,stocktwitsSentiment,random
74474,2023-04-26 11:00:00,AAPL,163.742,164.437,163.638,164.170,2358831.0,2.0,-0.418835,165.562124,...,15.114263,164.790267,165.079033,40.70,0.283625,26.0,29.0,341913.000000,0.5505,0.812824
74487,2023-04-26 11:00:00,ABBV,159.460,160.083,159.328,160.047,123589.0,2.0,0.173893,164.532857,...,20.108436,161.288133,160.192083,40.70,-0.734922,2.0,3.0,23.000000,0.4985,0.656799
74463,2023-04-26 11:00:00,ABT,108.412,108.686,108.391,108.461,153002.0,2.0,-0.208427,111.784528,...,23.918654,110.083533,107.858583,40.70,-0.414512,1.0,0.0,16515.846154,0.5750,0.249518
74470,2023-04-26 11:00:00,AMD,86.540,86.960,86.430,86.550,2666380.0,2.0,-0.952693,89.329752,...,7.950509,87.687467,89.002183,40.70,0.361374,6.0,8.0,10310.000000,0.5068,0.973137
74480,2023-04-26 11:00:00,AMZN,105.230,106.010,105.185,105.805,3517054.0,2.0,0.007377,108.701876,...,15.441857,105.373433,104.076983,40.70,0.516940,27.0,29.0,76166.000000,0.5424,0.157846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93086,2023-08-31 15:00:00,PM,96.320,96.490,96.000,96.430,145544.0,6.0,0.345266,97.324647,...,9.470432,96.170767,95.224883,21.48,-1.506299,2.0,8.0,58.000000,0.5857,0.388111
93087,2023-08-31 15:00:00,T,14.855,14.860,14.820,14.834,1694776.0,6.0,0.122452,14.927578,...,46.354675,14.565267,14.367500,21.48,-1.397089,2.0,0.0,49.000000,0.5000,0.492980
93061,2023-08-31 15:00:00,TSLA,258.545,259.480,258.460,258.910,4658465.0,6.0,4.504940,261.480532,...,40.129082,250.189600,241.647217,21.48,1.015369,196.0,174.0,873777.000000,0.5159,0.325042
93074,2023-08-31 15:00:00,TSM,93.880,93.995,93.790,93.795,282205.0,6.0,0.012457,95.859445,...,3.483295,94.304033,93.681733,21.48,-1.661768,3.0,0.0,842.000000,0.6770,0.417771
93089,2023-08-31 15:00:00,V,246.070,246.155,245.590,245.740,233902.0,6.0,0.831086,248.376832,...,7.555786,245.408500,243.221183,21.48,0.520599,4.0,0.0,32958.000000,0.5625,0.027965

In [38]:
train_set.to_csv('training_data_complete.csv', index=False)
test_set.to_csv('testing_data_complete.csv', index=False)